version: '3.1'

services:

  mongo:
    image: mongo
    # ... or for raspberry pi 2
    # image: apcheamitru/arm32v7-mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: <define-password>

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8011:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: <define-password>
   
  neon-server:
    image: tknapp/neon:latest
    # ... or for raspberry pi 2
    # image: tknapp/neon:latest-arm32v7
    restart: always
    ports:
      - 8010:80
    environment:
      MongoDb__Hostname: mongo
      MongoDb__Username: root
      MongoDb__Password: <define-password>
      ASPNETCORE_URLS: "http://+:80"
