// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neon.Infrastructure;

#nullable disable

namespace Infrastructure.Persistence.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20230305094250_AddedHtmlAssetType")]
    partial class AddedHtmlAssetType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Neon.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DisplayTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("NotAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("NotAfter");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("NotBefore");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Order");

                    b.Property<int>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasDiscriminator<int>("Type");
                });

            modelBuilder.Entity("Neon.Domain.HtmlAsset", b =>
                {
                    b.HasBaseType("Neon.Domain.Asset");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Neon.Domain.ImageAsset", b =>
                {
                    b.HasBaseType("Neon.Domain.Asset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ThumbnailContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasDiscriminator().HasValue(0);
                });
#pragma warning restore 612, 618
        }
    }
}
